namespace Notifications.Domain
{
    /// <summary>
    /// Human readable notification message generated by the LLM
    /// </summary>
    /// <param name="Category"></param>
    /// <param name="Summary"></param>
    /// <param name="SuggestedAction"></param>
    public sealed record GeneratedMessage(string Title, string Category, string Summary, string SuggestedAction)
    {
        public static readonly IReadOnlySet<string> allowedCategory = new HashSet<string>() 
            { "Availability", "Performance", "Security", "Data", "Configuration", "Maintenance", "Other" };

        public static GeneratedMessage Sanitise(string? title, string? category, string? summary, string? suggestedAction)
        {
            var cat = string.IsNullOrWhiteSpace(category) ? "Other" : category;
            return new GeneratedMessage(
                Truncate(string.IsNullOrWhiteSpace(title) ? "Notification" : title, 200),
                cat,
                Truncate(string.IsNullOrWhiteSpace(summary) ? "No summary available" : summary, 1000),
                Truncate(string.IsNullOrWhiteSpace(suggestedAction) ? "No suggested action available, Investigate the source system." : suggestedAction, 500)); 
        }

        // Truncate the summary and suggested action strings to a maximum length if required
        private static string Truncate(string value, int maxLength)
        {
            if (string.IsNullOrEmpty(value)) return value;
            return value.Length <= maxLength ? value : value[..maxLength];
        }
    }
}
